baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Richard Jarry's home directory"
  keywords = "homepage, blog, science, informatics, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  defaultTheme = "dark"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/RichardJarry1"

  [[params.social]]
    name = "email"
    url  = "mailto:richard.jarry@etu.esisar.grenoble-inp.fr"

  [[params.social]]
    name = "github"
    url  = "https://github.com/teuze"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/richard-jarry-01"

[languages]
  [languages.en]
    title = "Richard Jarry"
    homeSubtitle = "Sorcerer's Apprentice"
    keywords = ""
    copyright = "Richard Jarry-Randerson"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/"
      logoHomeLink = "/"

    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"

  [languages.fr]
    title = "Richard Jarry"
    homeSubtitle = "Apprenti Sorcier"
    keywords = ""
    copyright = "Richard Jarry-Randerson"
    readOtherPosts = "Lire d'autres articles"

    [languages.fr.params.logo]
      logoText = "cd /home/"
      logoHomeLink = "/fr/"

    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.fr.menu]
      [[languages.fr.menu.main]]
        identifier = "about"
        name = "À propos"
        url="../apropos"

      [[languages.fr.menu.main]]
        identifier = "blog"
        name = "Articles"
        url="../posts"

